#%RAML 1.0 Trait

headers:
  x-vio-transactionId:
    required: true
    type: string
    minLength: 36
    maxLength: 36
    example: "12345-124567-78564-9875-857654-89756"
  clientId:
    required: true
    type: string
    example: "jskdhfjkssdkfhdsfhdsfjdsfhdj"
  clientSecret:
    required: true
    type: string
    example: "jskdhfjkssdkfhdsfhdsfjdsfhdj"